
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}

  nginx:
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DOMAIN: ${DOMAIN}
      target: dev
    ports:
      - 443:443
    develop:
      watch:
        - path: ${NGINX_CONTEXT}/conf/ssl.conf
          target: /etc/nginx/conf.d/ssl.conf
          action: sync+restart
        - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
          target: /docker-entrypoint.sh
          action: sync+restart
        - path: ${NGINX_CONTEXT}/
          action: rebuild
