
# common
x-common-arguments: &common-arg
  BASE_IMAGE: ${BASE_IMAGE:?error}
  DOMAIN: ${DOMAIN:?error}
  
# development settings by Extensions and anchor
x-nginx-develop: &nginx-dev
  watch:
    - path: ${NGINX_CONTEXT}/conf/ssl.conf
      target: /etc/nginx/conf.d/ssl.conf
      action: sync+restart
    - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
      target: /docker-entrypoint.sh
      action: sync+restart
    - path: ${NGINX_CONTEXT}/
      action: rebuild

# network settings
x-inception-internal-network: &internal-container-network
  driver: bridge
  attachable: false
  internal: true
  enable_ipv4: true
  enable_ipv6: false

x-inception-external-network: &external-container-network
  driver: bridge
  attachable: false
  internal: false
  enable_ipv4: true
  enable_ipv6: false

# services
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    pull_policy: never
    image: mariadb:inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    networks:
      - backend-network
    configs:
      - source: mariadb_mariadb_config
        target: /etc/mysql/mariadb.cnf
        mode: 0440
      - source: mariadb_mariadb_server_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
        mode: 0440
      - source: mariadb_initdb_file
        target: /etc/mysql/init-file/wp.sql
        mode: 0440

  nginx:
    container_name: nginx
    hostname: nginx
    pull_policy: never
    image: nginx:inception
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DOMAIN: ${DOMAIN}
      target: prod
    ports:
      - 4430:443
    networks:
      - external-network
      - frontend-network
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0440
      - source: nginx_wordpress_config
        target: /etc/nginx/conf.d/ssl.conf
        mode: 0440
    develop:
      <<: *nginx-dev

  wordpress:
    container_name: wordpress
    hostname: wordpress
    pull_policy: never
    image: wordpress:inception
    build:
      context: ${WORDPRESS_CONTEXT}
      dockerfile: Dockerfile
      args:
        <<: *common-arg
    networks:
      - frontend-network
      - backend-network
    configs:
      - source: wordpress_php_fpm_config
        target: /etc/php/7.4/fpm/php-fpm.conf
        mode: 440
      - source: wordpress_php_fpm_php_ini
        target: /etc/php/7.4/fpm/php.ini
        mode: 440
      - source: wordpress_php_fpm_pool_dir
        target: /etc/php/7.4/fpm/pool.d
        mode: 750

# configs
configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx/nginx.conf
  nginx_wordpress_config:
    file: ./requirements/nginx/conf/ssl.conf
  wordpress_php_fpm_config:
    file: ${WORDPRESS_CONTEXT}/conf/fpm/php-fpm.conf
  wordpress_php_fpm_php_ini:
    file: ${WORDPRESS_CONTEXT}/conf/fpm/php.ini
  wordpress_php_fpm_pool_dir:
    file: ${WORDPRESS_CONTEXT}/conf/fpm/pool.d
  mariadb_mariadb_config:
    file: ${MARIADB_CONTEXT}/conf/mysql/mariadb.cnf
  mariadb_mariadb_server_config:
    file: ${MARIADB_CONTEXT}/conf/mysql/mariadb.conf.d/50-server.cnf
  mariadb_initdb_file:
    file: ${MARIADB_CONTEXT}/conf/mysql/init-file/wp.sql

# network
networks:
  external-network:
    name: inception-external
    <<: *external-container-network
  frontend-network:
    name: inception-frontend
    <<: *internal-container-network
  backend-network:
    name: inception-backend
    <<: *internal-container-network
