
# common
x-common-arguments: &common-arg
  BASE_IMAGE: ${BASE_IMAGE:?error}
  DOMAIN: ${DOMAIN:?error}
  
# development settings by Extensions and anchor
x-nginx-develop: &nginx-dev
  watch:
    - path: ${NGINX_CONTEXT}/conf/ssl.conf
      target: /etc/nginx/conf.d/ssl.conf
      action: sync+restart
    - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
      target: /docker-entrypoint.sh
      action: sync+restart
    - path: ${NGINX_CONTEXT}/
      action: rebuild

x-mariadb-develop: &mariadb-dev
  watch:
    - path: ${MARIADB_CONTEXT}/tools/docker-entrypoint.sh
      action: rebuild
    - path: ${MARIADB_CONTEXT}/conf
      action: restart

# network settings
x-inception-internal-network: &internal-container-network
  driver: bridge
  attachable: false
  internal: true

x-inception-external-network: &external-container-network
  driver: bridge
  attachable: false
  internal: false

# services
services:
  mariadb:
    restart: on-failure
    container_name: mariadb
    hostname: mariadb
    pull_policy: never
    image: mariadb:inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    env_file: ${MARIADB_CONTEXT}/.env
    environment:
      ROOT_PASS_FILE: ${ROOT_PASS_FILE}
      WP_DB_PASS_FILE: ${WP_DB_PASS_FILE}
    healthcheck:
      test: ["CMD-SHELL", "ps -p 1 | grep mariadbd"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend-network
    configs:
      - source: mariadb_mariadb_config
        target: /etc/mysql/mariadb.cnf
      - source: mariadb_mariadb_server_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: db_root_password
        target: ${ROOT_PASS_FILE}
      - source: wp_db_pass_file
        target: /mariadb/wordpress-password
    volumes:
      - mariadbd-data:/var/lib/mysql
    develop:
      <<: *mariadb-dev

  nginx:
    restart: on-failure
    container_name: nginx
    hostname: nginx
    pull_policy: never
    image: nginx:inception
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DOMAIN: ${DOMAIN}
      target: prod
    ports:
      - ${OPEN_PORT}:443
    env_file: ${NGINX_CONTEXT}/.env
    environment:
      SSL_CRT_MOUNT_PATH: ${SSL_CRT_MOUNT_PATH}
      SSL_KEY_MOUNT_PATH: ${SSL_KEY_MOUNT_PATH}
    networks:
      - external-network
      - frontend-network
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_wordpress_config
        target: /etc/nginx/conf.d/ssl.conf
    secrets:
      - source: ssl_crt
        target: ${SSL_CRT_MOUNT_PATH:?error}
      - source: ssl_key
        target: ${SSL_KEY_MOUNT_PATH:?error}
    volumes:
      - wordpress-data:/srv/wordpress/
    develop:
      <<: *nginx-dev
    depends_on:
      - wordpress

  wordpress:
    restart: on-failure
    container_name: wordpress
    hostname: wordpress
    pull_policy: never
    image: wordpress:inception
    build:
      context: ${WORDPRESS_CONTEXT}
      dockerfile: Dockerfile
      args:
        <<: *common-arg
    env_file: ${WORDPRESS_CONTEXT}/.env
    environment:
      WP_DB_PASS_FILE: ${WP_DB_PASS_FILE}
    networks:
      - frontend-network
      - backend-network
    configs:
      - source: wordpress_php_fpm_pool_dir
        target: /etc/php/7.4/fpm/pool.d
    secrets:
      - source: wp_db_pass_file
        target: /mariadb/wordpress-password
    volumes:
      - wordpress-data:/srv/wordpress/
    depends_on:
      mariadb:
        condition: service_healthy

# configs
configs:
  nginx_config:
    file: ${NGINX_CONTEXT}/dist/conf/nginx.conf
  nginx_wordpress_config:
    file: ${NGINX_CONTEXT}/dist/conf/conf.d/ssl.conf
  wordpress_php_fpm_pool_dir:
    file: ${WORDPRESS_CONTEXT}/dist/conf/fpm/pool.d
  mariadb_mariadb_config:
    file: ${MARIADB_CONTEXT}/dist/conf/mysql/mariadb.cnf
  mariadb_mariadb_server_config:
    file: ${MARIADB_CONTEXT}/dist/conf/mysql/mariadb.conf.d/50-server.cnf

# secrets
secrets:
  ssl_key:
    file: ${SECRETS_CONTEXT}/nginx/ssl.key
  ssl_crt:
    file: ${SECRETS_CONTEXT}/nginx/ssl.crt
  db_root_password:
    file: ${SECRETS_CONTEXT}/db_root_password.txt
  wp_db_pass_file:
    file: ${SECRETS_CONTEXT}/db_password.txt

# volumes
volumes:
  wordpress-data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/wordpress-core
  mariadbd-data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/mariadbd-data

# network
networks:
  external-network:
    name: inception-external
    <<: *external-container-network
  frontend-network:
    name: inception-frontend
    <<: *external-container-network
  backend-network:
    name: inception-backend
    <<: *internal-container-network
