
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}

  nginx:
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    ports:
      - 8000:80
    develop:
      watch:
        - path: ${NGINX_CONTEXT}/conf/ssl.cnf
          target: /etc/nginx/conf.d/ssl.cnf
          action: sync+restart
        - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
          target: /docker-entrypoint.sh
          action: sync+restart
        - path: ${NGINX_CONTEXT}/
          action: rebuild
