
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    expose:
      - 8000:80
