
# common
x-common-arguments: &common-arg
  BASE_IMAGE: ${BASE_IMAGE:?error}
  DOMAIN: ${DOMAIN:?error}
  
# development settings by Extensions and anchor
x-nginx-develop: &nginx-dev
  watch:
    - path: ${NGINX_CONTEXT}/conf/ssl.conf
      target: /etc/nginx/conf.d/ssl.conf
      action: sync+restart
    - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
      target: /docker-entrypoint.sh
      action: sync+restart
    - path: ${NGINX_CONTEXT}/
      action: rebuild

# network settings
x-inception-internal-network: &internal-container-network
  driver: bridge
  attachable: false
  internal: true
  enable_ipv4: true
  enable_ipv6: false

x-inception-external-network: &external-container-network
  driver: bridge
  attachable: false
  internal: false
  enable_ipv4: true
  enable_ipv6: false

# services
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    pull_policy: never
    image: mariadb:inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    networks:
      - backend-network

  nginx:
    container_name: nginx
    hostname: nginx
    pull_policy: never
    image: nginx:inception
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DOMAIN: ${DOMAIN}
      target: prod
    ports:
      - 4430:443
    networks:
      - external-network
      - frontend-network
    develop:
      <<: *nginx-dev

  wordpress:
    container_name: wordpress
    hostname: wordpress
    pull_policy: never
    image: wordpress:inception
    build:
      context: ${WORDPRESS_CONTEXT}
      dockerfile: Dockerfile
      args:
        <<: *common-arg
    networks:
      - frontend-network
      - backend-network

# network
networks:
  external-network:
    name: inception-external
    <<: *external-container-network
  frontend-network:
    name: inception-frontend
    <<: *internal-container-network
  backend-network:
    name: inception-backend
    <<: *internal-container-network
