
# common
x-common-arguments: &common-arg
  BASE_IMAGE: ${BASE_IMAGE:?error}
  DOMAIN: ${DOMAIN:?error}
  
# development settings by Extensions and anchor
x-nginx-develop: &nginx-dev
  watch:
    - path: ${NGINX_CONTEXT}/conf/ssl.conf
      target: /etc/nginx/conf.d/ssl.conf
      action: sync+restart
    - path: ${NGINX_CONTEXT}/conf/docker-entrypoint.sh
      target: /docker-entrypoint.sh
      action: sync+restart
    - path: ${NGINX_CONTEXT}/
      action: rebuild

# services
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}

  nginx:
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DOMAIN: ${DOMAIN}
      target: prod
    ports:
      - 4430:443
    develop:
      <<: *nginx-dev

  wordpress:
    build:
      context: ${WORDPRESS_CONTEXT}
      dockerfile: Dockerfile
      args:
        <<: *common-arg
    ports:
      - 8000:80
    command: "cat"
    tty: true
    init: true
