CREATE USER IF NOT EXISTS wordpress IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS wordpress;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
	ON wordpress.*
	TO wordpress
	IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
